[pytest]

addopts = --headed
          --browser=chromium
          --base-url=https://www.saucedemo.com
          --html=/Users/lucky/PycharmProjects/PlaywrightFW1/reports/report.html
          --self-contained-html